### ISSUE TITLE
Là một người dùng, tôi có thể tải lên các tập tin sách điện tử ở các định dạng phổ biến để có thể truy cập vào các tài liệu đọc mà tôi sở hữu.

### ISSUE THREAD

**Issue by Lehoangminh-dab** [Lehoangminh-dab/HCI---INT2041-57---Dyslexic-E-Reader#1]
_Figma Pages: Library_
# STRINGS
- FOLDER_UPLOADS_PATH: {/data/data/[package_name]/files/[file_name].txt}
# TASKS
- [ ] **Tạo File Kiểm Thử**: Tạo 1 file EPUB, PDF, DOCX, JPEG, PNG để vào [FOLDER_UPLOADS_PATH] 
- [x] **Tạo Nút Xem Thư Viện**: Hiển thị nút "Import a File" trên trang "Library"  của ứng dụng.
- [x] **Mở Bộ Lưu Trữ Thiết Bị**: Khi nút tải được bấm, hiển thị một trình khám phá tập tin của bộ nhớ thiết bị của người dùng, lọc để chỉ hiển thị các tập tin EPUB, PDF, JPEG, DOCX, PNG.
- [x] **Chọn Tập Tin Của Người Dùng**: Cho phép người dùng điều hướng và chọn một tập tin để tải lên.
- [x] **Tải Lên**: Convert file được chọn thành .txt, tạo một bản copy và đặt nó vào folder path [FOLDER_UPLOADS_PATH] của ứng dụng. Nếu folder "Uploads" chưa tồn tại, hệ thống sẽ tự động tạo mới. Nếu đã tồn tại, hệ thống sẽ ghi đè lên folder cũ. Nếu không thuộc cả 2 trường hợp trên, hê thống sẽ trả lại lỗi.
- [x] **Tải Lên Thành Công**: Hiển thị thông báo tập tin đã tải lên thành công.
- [x] **Tải Lên Thất Bại**: Hiển thị thông báo lỗi nếu quá trình tải lên mất quá lâu hoặc xảy ra lỗi trong mã ứng dụng.
